self: system:
let
  inherit (self.inputs.nixpkgs.legacyPackages.${system}.extend self.overlays.nvim-treesitter-main)
    lib
    nurl
    vimPlugins
    writers
    ;
  inherit (lib.meta) getExe;
  inherit (lib.strings) makeBinPath;
in
getExe (
  writers.makeScriptWriter
    {
      interpreter = "${
        getExe (self.packages.${system}.neovim.override { plugins = [ vimPlugins.nvim-treesitter ]; })
      } -l";
      makeWrapperArgs = [
        "--prefix"
        "PATH"
        ":"
        "${makeBinPath [ nurl ]}"
      ];
    }

    "/bin/generate"

    # lua
    ''
      local util = require("nvim-treesitter.util")
      local parsers = require("nvim-treesitter.parsers")

      ---@param str string
      local function surround(str)
      	return '"' .. str .. '"'
      end

      local jobs = {} ---@type table<string,vim.SystemObj|false>
      local grammars = {} ---@type string[]
      for k, p in pairs(parsers) do
      	if p.install_info then
      		local info = p.install_info

      		assert(info.path == nil and info.queries == nil)

      		jobs[k] = vim.system({ "nurl", info.url, info.revision, "--indent=6" }, { text = true })
      	else
      		jobs[k] = false
      	end

      	if #vim.tbl_keys(jobs) % 100 == 0 or next(parsers, k) == nil then
      		for name, job in pairs(jobs) do
      			local parser = parsers[name]

      			local attrs = {}
      			local function insert(key, value)
      				table.insert(attrs, "      " .. key .. " = " .. value .. ";\n")
      			end

      			insert("name", surround(name))
      			insert("tier", parser.tier)

      			if job then
      				local info = parser.install_info

      				insert("revision", surround("0.0.0+rev=" .. info.revision:sub(1, 7)))
      				insert("src", job:wait().stdout)
      				if info.location then
      					insert("location", surround(info.location))
      				end
      				if info.generate then
      					insert("generate", "true")
      				end
      				if info.generate_from_json ~= nil then
      					insert("generate_from_json", "false")
      				end
      			else
      				insert("revision", surround("0.0.0+rev=main"))
      			end

      			if parser.requires then
      				insert("requires", "attrValues { inherit (grammars) " .. table.concat(parser.requires, " ") .. "; }")
      			end

      			grammars[#grammars + 1] = "    " .. name .. " = buildGrammar {\n" .. table.concat(attrs) .. "    };\n"

      			jobs[name] = nil
      		end
      	end
      end

      assert(#vim.tbl_keys(jobs) == 0)

      table.sort(grammars)

      util.write_file("overlays/nvim-treesitter-main/generated.nix", [[
      # generated by nix run .\#generate

      {
        buildGrammar,
        ]] .. vim.system({ "nurl", "-Ls", ",\n  " }, { text = true }):wait().stdout .. [[,
      }:

      let
        inherit (builtins) attrValues;

        grammars = {
      ]] .. table.concat(grammars) .. [[
        };
      in
      grammars
      ]])
    ''
)
